name: Render and Publish Quarto Website

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release
        env:
          QUARTO_LOG_LEVEL: warning

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
        env:
          R_COMPILE_AND_INSTALL_PACKAGES: never

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.19.1
          cache: true

      - name: Install dependencies with pixi
        run: pixi install --verbose

      - name: Restore R package cache
        uses: r-lib/actions/setup-renv@v2

      - name: Render Quarto Project
        run: |
          pixi run quarto render

      - name: Setup Pages
        uses: actions/configure-pages@v4
        if: github.ref == 'refs/heads/master'

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        if: github.ref == 'refs/heads/master'
        with:
          path: ./_site

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4